In [1]:
#라이브러리 호출
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor , GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [2]:
#원본 데이터 (깃허브에 저장된 데이터 파일 호출)
df1 = pd.read_csv('https://github.com/lhmlhm1111/Data_GongHak/raw/master/11-22totaldata.txt',encoding='utf-8',sep=',')

final = pd.read_csv('https://github.com/lhmlhm1111/Data_GongHak/raw/master/%EC%A0%84%EC%B2%98%EB%A6%AC/%EC%B5%9C%EC%8B%A0%EB%8D%B0%EC%9D%B4%ED%84%B0/test_data_final.csv',encoding='UTF-8',sep=',')

In [3]:
# 회의 때 변수 선별 3가지 방법 univariate, importance , heat map상관관계도 로 선별한 6가지
# 소득 , 인구밀도 , 사업체수 , 장애등급별 장애인현황 ,독거노인수 , 노령화지수
# 로 Train , Test 머신러닝 한 과정입니다

In [4]:
#학습/테스트 데이터
x = df1.drop(['year','읍면동명','자치구','새누리당','더불어민주당','국민의당','선거인수','유년부양비','노년부양비','종사자수','사업체 창업률','기초수급자인원수','보육시설','금융기관','사업체 평균연령','인구','면적'],axis=1)
y = df1['새누리당']

x_train, x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [45]:

## 랜덤포레스트 회귀 모델 ( 새누리당 예측 ! )

rf1 = GradientBoostingRegressor()

rf1.fit(x_train, y_train)

predicted = rf1.predict(x_test)

print(predicted)

[3043.23118777 2093.08666559 4911.10679928 5673.10445635 4888.8618203
 4424.27157113 5583.42181463 3245.06417521 3815.41213374 3434.48806192
 4364.27115386  996.59310992 2834.34594363 3087.42350511 5810.71405463
 3841.01970552 4156.60909102 5823.27266562 4038.22620053 1726.66641918
 3071.26514886 7882.44339477 3220.82087471 3497.34076623 4632.68398833
 3142.69251472 3403.46749962 6605.90262797 4686.43901316 5435.1519135
 5385.1059696  3340.35502177 4392.45543145 3374.31311152 6814.68198302
 7272.41104554 5208.49910667 3544.43702731 2639.44040153 5980.32489631
 4443.60208778 3574.79327127 3431.35641998 6451.24273013 6042.57116807
 1765.41126303 4486.58882845 6139.09369028 7444.98247615 3995.77475567
 3709.55700193 4420.66178774 4643.89051182 4983.26868427 3507.13973226
 5346.33457858 6099.24609926 2034.85362721 5970.6017433  2192.47284444
 2176.52921517 6388.04861496 3473.75398161 2033.1951735  3690.7682534
 3819.66033073 8473.70431817 2314.99690269 6432.06864177 5217.38214029
 2757.933

In [6]:
#적합값의 편차
predicted.std()

1618.4766512882177

In [7]:
#원래 데이터값의 편차
y_test.std()

2154.674807628107

In [8]:
#적합값과 원래 데이터값 사이 편차
np.sqrt(mean_squared_error(y_test,predicted))

1422.3777564581055

In [54]:
#원래 데이터의 새누리당 값 (test로 쓰인것)
y_test

774     2887.0
375     1594.0
185     4242.0
464     6186.0
710     5093.0
298     5336.0
839     4512.0
745     2883.0
750     3963.0
726     5674.0
8       3792.0
392      929.0
286        0.0
773     2462.0
832     2695.0
467     4152.0
558     5359.0
216     7549.0
600     4756.0
84      1701.0
507        0.0
307     9530.0
672     3880.0
482     5647.0
582     5701.0
677     2930.0
370     3458.0
238     7134.0
717     4678.0
736     4904.0
        ...   
549     4711.0
756     4493.0
758    10603.0
651     3930.0
472     5135.0
119     4825.0
207     3334.0
453     7458.0
368     1106.0
341     3298.0
247     4402.0
202     3406.0
120     3299.0
255     2759.0
697     3941.0
194     3212.0
676     2694.0
755     3403.0
614     8343.0
311     4426.0
565     6760.0
195     2796.0
61      3127.0
522     2195.0
340     3353.0
687        0.0
447     6402.0
436     6916.0
544     3328.0
680     5935.0
Name: 새누리당, Length: 170, dtype: float64

In [10]:
#상관계수 히트맵 (참고용으로 넣어둠)

import seaborn as sns
import matplotlib.pyplot as plt

z = df1.drop(['year','읍면동명','자치구','선거인수','유년부양비','노년부양비','종사자수','사업체 창업률','기초수급자인원수','보육시설','금융기관','사업체 평균연령','인구','면적'],axis=1)

plt.rc('font', family='Malgun Gothic')

fig = plt.figure(figsize=[20,20])

ax=sns.heatmap(z.corr(),annot=True,square=True)

In [20]:
print(rf1.score(x_train, y_train))

0.8146555349400233


In [39]:
final_x = final.drop(final.columns[0:2],axis=1)

In [41]:
predict1 = rf1.predict(final_x)

In [17]:
a=['인구밀도','사업체수','장애등급','독거노인수','노령화지수']
for i in range(5):
    final[a[i]]=final[a[i]].fillna(final[a[i]].median())


In [23]:
df4 = pd.DataFrame(predict_final,columns=['새누리당'])


In [28]:
final1 = pd.concat([df5,df4],axis=1)

In [25]:
df5 = final.drop(final.columns[2:],axis=1)

In [48]:
predicted

array([3043.23118777, 2093.08666559, 4911.10679928, 5673.10445635,
       4888.8618203 , 4424.27157113, 5583.42181463, 3245.06417521,
       3815.41213374, 3434.48806192, 4364.27115386,  996.59310992,
       2834.34594363, 3087.42350511, 5810.71405463, 3841.01970552,
       4156.60909102, 5823.27266562, 4038.22620053, 1726.66641918,
       3071.26514886, 7882.44339477, 3220.82087471, 3497.34076623,
       4632.68398833, 3142.69251472, 3403.46749962, 6605.90262797,
       4686.43901316, 5435.1519135 , 5385.1059696 , 3340.35502177,
       4392.45543145, 3374.31311152, 6814.68198302, 7272.41104554,
       5208.49910667, 3544.43702731, 2639.44040153, 5980.32489631,
       4443.60208778, 3574.79327127, 3431.35641998, 6451.24273013,
       6042.57116807, 1765.41126303, 4486.58882845, 6139.09369028,
       7444.98247615, 3995.77475567, 3709.55700193, 4420.66178774,
       4643.89051182, 4983.26868427, 3507.13973226, 5346.33457858,
       6099.24609926, 2034.85362721, 5970.6017433 , 2192.47284

In [31]:
final1

읍면동명  자치구         새누리당
0        신사동  강남구  1418.163899
1        신사동  관악구  3246.691441
2       논현1동  강남구  1691.979019
3       논현2동  강남구  1691.979019
4       압구정동  강남구  1691.979019
5        청담동  강남구  1691.979019
6       역삼1동  강남구  2689.257189
7       역삼2동  강남구  2370.678811
8       삼성1동  강남구  1030.482326
9       삼성2동  강남구  1585.262700
10      대치1동  강남구  1357.814337
11      대치2동  강남구  2751.148672
12      대치4동  강남구  1311.447581
13      도곡1동  강남구  1823.322849
14      도곡2동  강남구  2097.137968
15      개포1동  강남구  1258.243670
16      개포2동  강남구  1141.284972
17      개포4동  강남구  2097.137968
18      일원본동  강남구  3355.398161
19      일원1동  강남구  4037.276393
20      일원2동  강남구  3936.312757
21       수서동  강남구  3858.815706
22       세곡동  강남구  3903.352993
23       강일동  강동구  4501.039450
24       상일동  강동구  2000.658569
25      명일1동  강동구  2853.860961
26      명일2동  강동구  2019.311029
27      고덕1동  강동구  2747.978663
28      고덕2동  강동구  2068.207114
29      암사1동  강동구  4742.306352
..       ...  ...          ...
394      광희동   중구  1133.448263
395     을지로동   중구   809.680082
396      신당동   중구  1436.991926
397      다산동   중구  2681.624501
398      약수동   중구  3253.030210
399      청구동   중구  2687.963270
400     신당5동   중구  1682.170928
401      동화동   중구  1726.843449
402      황학동   중구  2097.137968
403      중림동   중구  2000.658569
404    금호1가동   중구  2950.953162
405  금호2.3가동   중구  2950.953162
406    금호4가동   중구  2950.953162
407      옥수동   중구  2950.953162
408     면목본동  중랑구  4815.594927
409     면목2동  중랑구  4479.946458
410   면목3.8동  중랑구  4443.606025
411     면목4동  중랑구  4292.379767
412     면목5동  중랑구  1802.781665
413     면목7동  중랑구  3987.204744
414     상봉2동  중랑구  2798.154868
415     망우3동  중랑구  3635.930550
416     상봉1동  중랑구  4347.304625
417     중화1동  중랑구  3195.743373
418     중화2동  중랑구  4742.306352
419      묵1동  중랑구  4391.228479
420      묵2동  중랑구  3387.843362
421     망우본동  중랑구  4201.041630
422     신내1동  중랑구  4236.254561
423     신내2동  중랑구  4088.694006

[424 rows x 3 columns]

In [55]:
# 더불어 민주당 예측하기!

x2 = df1.drop(['year','읍면동명','자치구','새누리당','더불어민주당','국민의당','선거인수','유년부양비','노년부양비','종사자수','사업체 창업률','기초수급자인원수','보육시설','금융기관','사업체 평균연령','인구','면적'],axis=1)
y2 = df1['더불어민주당']

x2_train, x2_test , y2_train , y2_test = train_test_split(x2,y2,test_size=0.2,random_state=1)

In [68]:
rf2 = RandomForestRegressor()

rf2.fit(x2_train, y2_train)


C:\Users\Hosik\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [69]:
predict2 = rf2.predict(final_x)

In [70]:
predict2

array([ 949.9, 2697. , 2297.9, 2357.8, 2355.5, 2312. , 2869. , 2960.4,
        796.5, 2567.9,  940.6, 2688.1, 1168.5, 1824. , 2433.4, 1183.8,
       1266.5, 2569.3, 2528.1, 3805.1, 2722.8, 2558.7, 2912.2, 3069.8,
       2381.5, 2382.5, 2381.5, 2634.7, 2238. , 3391.3, 2502.7, 2338.6,
       4383.7, 2630.7, 4383.7, 3286.3, 2928.2, 3167.9, 2843.6,  386.2,
       2417.7, 2417.7, 3069.8, 2874.6, 2389.8, 3637.2, 2963.3, 2558.7,
       2934.1, 2511.5, 3470. , 4036.8, 3069.8, 2949.7, 4383.7, 2750.2,
       2633.6, 2932.1, 2797.5, 4369.8, 3284.1, 2333.2, 2643.6, 2874.6,
       2767.4, 2417.7, 2909.3, 2668.9, 2869. , 1903.6, 3304.2, 4383.7,
       4435.9, 2949.7, 2389.8, 3001.1, 3069.8, 2381.5, 2700.3, 2932.1,
       2479.4, 2381.5, 2697. , 2502.7, 2238. , 2952.3, 2630.7, 3069.8,
       2528.1, 2633.6, 2633.6, 2697. , 3032.3, 2275.9, 2718. , 2357.1,
       2750.2, 2630.7, 1266.5, 2572.5, 2643.6, 2382.5, 2351. , 2869. ,
       2357.1, 2767.4, 2697. , 2479.4, 2475.6, 4353.7, 2874.6, 3001.1,
      

In [78]:
#국민의당 예측!

x3 = df1.drop(['year','읍면동명','자치구','새누리당','더불어민주당','국민의당','선거인수','유년부양비','노년부양비','종사자수','사업체 창업률','기초수급자인원수','보육시설','금융기관','사업체 평균연령','인구','면적'],axis=1)
y3 = df1['국민의당']

x3_train, x3_test , y3_train , y3_test = train_test_split(x3,y3,test_size=0.2,random_state=1)

In [95]:
rf3 = RandomForestRegressor()

rf3.fit(x3_train, y3_train)


C:\Users\Hosik\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [96]:
predict3 = rf3.predict(final_x)

In [97]:
predict3

array([4558.9, 5958.9, 4558.9, 4558.9, 4558.9, 4558.9, 4558.9, 4558.9,
       4558.9, 4558.9, 5417.8, 4558.9, 4558.9, 5250.6, 5250.6, 4918.5,
       4918.5, 4568.1, 4918.5, 4360. , 4892.3, 6319.1, 7032. , 4928.1,
       4918.5, 5250.6, 5417.8, 4918.5, 5250.6, 4956.6, 4918.5, 4918.5,
       8306.8, 5114.5, 5894. , 5050.5, 4701.3, 4510.9, 4279.9, 4918.5,
       5509.9, 5509.9, 4872.4, 5381.9, 5391.6, 3530.7, 4892.3, 6188.2,
       5281.7, 5092.7, 4360. , 4541. , 4972.6, 6648.5, 6388.6, 4918.5,
       5958.9, 5391.6, 5083. , 3690.6, 4510.9, 5335.3, 4918.5, 5437.1,
       5677.1, 5450.4, 5081. , 6548.7, 5100. , 6165.9, 4510.9, 5424.4,
       4563.9, 6648.5, 5391.6, 6188.2, 4898. , 4918.5, 4918.5, 5391.6,
       5450.4, 5417.8, 5459.6, 4918.5, 5250.6, 3738.8, 5114.5, 4898. ,
       4918.5, 5958.9, 5459.6, 5958.9, 4898. , 5250.6, 5250.6, 5791.7,
       5417.8, 5114.5, 4918.5, 5391.6, 5417.8, 5250.6, 5791.7, 4630.4,
       5791.7, 5677.1, 5958.9, 4901.1, 3738.8, 3881.2, 5381.9, 5323.1,
      

In [98]:
#더불어민주당을 새누리당에 추가하기
df7 = pd.DataFrame(predict2,columns=['더불어민주당'])

In [99]:
final2 = pd.concat([final1,df7],axis=1)

In [101]:
final2

읍면동명  자치구         새누리당  더불어민주당
0        신사동  강남구  1418.163899   949.9
1        신사동  관악구  3246.691441  2697.0
2       논현1동  강남구  1691.979019  2297.9
3       논현2동  강남구  1691.979019  2357.8
4       압구정동  강남구  1691.979019  2355.5
5        청담동  강남구  1691.979019  2312.0
6       역삼1동  강남구  2689.257189  2869.0
7       역삼2동  강남구  2370.678811  2960.4
8       삼성1동  강남구  1030.482326   796.5
9       삼성2동  강남구  1585.262700  2567.9
10      대치1동  강남구  1357.814337   940.6
11      대치2동  강남구  2751.148672  2688.1
12      대치4동  강남구  1311.447581  1168.5
13      도곡1동  강남구  1823.322849  1824.0
14      도곡2동  강남구  2097.137968  2433.4
15      개포1동  강남구  1258.243670  1183.8
16      개포2동  강남구  1141.284972  1266.5
17      개포4동  강남구  2097.137968  2569.3
18      일원본동  강남구  3355.398161  2528.1
19      일원1동  강남구  4037.276393  3805.1
20      일원2동  강남구  3936.312757  2722.8
21       수서동  강남구  3858.815706  2558.7
22       세곡동  강남구  3903.352993  2912.2
23       강일동  강동구  4501.039450  3069.8
24       상일동  강동구  2000.658569  2381.5
25      명일1동  강동구  2853.860961  2382.5
26      명일2동  강동구  2019.311029  2381.5
27      고덕1동  강동구  2747.978663  2634.7
28      고덕2동  강동구  2068.207114  2238.0
29      암사1동  강동구  4742.306352  3391.3
..       ...  ...          ...     ...
394      광희동   중구  1133.448263   398.5
395     을지로동   중구   809.680082   293.0
396      신당동   중구  1436.991926   812.6
397      다산동   중구  2681.624501  2661.7
398      약수동   중구  3253.030210  2697.0
399      청구동   중구  2687.963270  2980.1
400     신당5동   중구  1682.170928  2162.5
401      동화동   중구  1726.843449  1922.0
402      황학동   중구  2097.137968  2433.4
403      중림동   중구  2000.658569  2381.5
404    금호1가동   중구  2950.953162  2633.6
405  금호2.3가동   중구  2950.953162  2633.6
406    금호4가동   중구  2950.953162  2633.6
407      옥수동   중구  2950.953162  2633.6
408     면목본동  중랑구  4815.594927  4275.4
409     면목2동  중랑구  4479.946458  4036.8
410   면목3.8동  중랑구  4443.606025  4036.8
411     면목4동  중랑구  4292.379767  2746.3
412     면목5동  중랑구  1802.781665  2502.7
413     면목7동  중랑구  3987.204744  2948.1
414     상봉2동  중랑구  2798.154868  2348.0
415     망우3동  중랑구  3635.930550  2832.7
416     상봉1동  중랑구  4347.304625  3032.3
417     중화1동  중랑구  3195.743373  2697.0
418     중화2동  중랑구  4742.306352  4605.6
419      묵1동  중랑구  4391.228479  2630.7
420      묵2동  중랑구  3387.843362  2414.4
421     망우본동  중랑구  4201.041630  4275.4
422     신내1동  중랑구  4236.254561  3479.8
423     신내2동  중랑구  4088.694006  3032.3

[424 rows x 4 columns]

In [102]:
final2.to_csv('final_predict_y.csv',index=False)