In [23]:
#라이브러리 호출
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor , GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [24]:
#원본 데이터 (깃허브에 저장된 데이터 파일 호출)
df1 = pd.read_csv('https://github.com/lhmlhm1111/Data_GongHak/raw/master/11-22totaldata.txt',encoding='utf-8',sep=',')

final = pd.read_csv('https://github.com/lhmlhm1111/Data_GongHak/raw/master/%EC%A0%84%EC%B2%98%EB%A6%AC/%EC%B5%9C%EC%8B%A0%EB%8D%B0%EC%9D%B4%ED%84%B0/test_data_final.csv',encoding='UTF-8',sep=',')

In [25]:
# 회의 때 변수 선별 3가지 방법 univariate, importance , heat map상관관계도 로 선별한 6가지
# 소득 , 인구밀도 , 사업체수 , 장애등급별 장애인현황 ,독거노인수 , 노령화지수
# 로 Train , Test 머신러닝 한 과정입니다

In [26]:
#학습/테스트 데이터
x = df1.drop(['year','읍면동명','자치구','새누리당','더불어민주당','국민의당','선거인수','유년부양비','노년부양비','종사자수','사업체 창업률','기초수급자인원수','보육시설','금융기관','사업체 평균연령','인구','면적'],axis=1)
y = df1['새누리당']

x_train, x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [27]:

## 랜덤포레스트 회귀 모델 ( 새누리당 예측 ! )

rf1 = GradientBoostingRegressor()

rf1.fit(x_train, y_train)

predicted = rf1.predict(x_test)

print(predicted)

[3043.23118777 2093.08666559 4911.10679928 5673.10445635 4888.8618203
 4424.27157113 5583.42181463 3245.06417521 3815.41213374 3434.48806192
 4364.27115386  996.59310992 2834.34594363 3087.42350511 5810.71405463
 3841.01970552 4156.60909102 5823.27266562 4038.22620053 1726.66641918
 3071.26514886 7882.44339477 3220.82087471 3497.34076623 4186.19042358
 3142.69251472 3403.46749962 6605.90262797 4686.43901316 5435.1519135
 5385.1059696  3340.35502177 4392.45543145 3374.31311152 6814.68198302
 7272.41104554 5208.49910667 3544.43702731 2639.44040153 5980.32489631
 4443.60208778 3574.79327127 3431.35641998 6451.24273013 6042.57116807
 1765.41126303 4486.58882845 6139.09369028 7444.98247615 3995.77475567
 3709.55700193 4420.66178774 4643.89051182 4983.26868427 3507.13973226
 5346.33457858 6099.24609926 2034.85362721 5970.6017433  2192.47284444
 2176.52921517 6388.04861496 3473.75398161 2033.1951735  3690.7682534
 3819.66033073 8473.70431817 2314.99690269 6432.06864177 5217.38214029
 2757.933

In [28]:
#적합값의 편차
predicted.std()

1617.7331523743171

In [29]:
#원래 데이터값의 편차
y_test.std()

2154.674807628107

In [30]:
#적합값과 원래 데이터값 사이 편차
np.sqrt(mean_squared_error(y_test,predicted))

1421.6218714598633

In [31]:
#원래 데이터의 새누리당 값 (test로 쓰인것)
y_test

774     2887.0
375     1594.0
185     4242.0
464     6186.0
710     5093.0
298     5336.0
839     4512.0
745     2883.0
750     3963.0
726     5674.0
8       3792.0
392      929.0
286        0.0
773     2462.0
832     2695.0
467     4152.0
558     5359.0
216     7549.0
600     4756.0
84      1701.0
507        0.0
307     9530.0
672     3880.0
482     5647.0
582     5701.0
677     2930.0
370     3458.0
238     7134.0
717     4678.0
736     4904.0
        ...   
549     4711.0
756     4493.0
758    10603.0
651     3930.0
472     5135.0
119     4825.0
207     3334.0
453     7458.0
368     1106.0
341     3298.0
247     4402.0
202     3406.0
120     3299.0
255     2759.0
697     3941.0
194     3212.0
676     2694.0
755     3403.0
614     8343.0
311     4426.0
565     6760.0
195     2796.0
61      3127.0
522     2195.0
340     3353.0
687        0.0
447     6402.0
436     6916.0
544     3328.0
680     5935.0
Name: 새누리당, Length: 170, dtype: float64

In [32]:
#상관계수 히트맵 (참고용으로 넣어둠)

import seaborn as sns
import matplotlib.pyplot as plt

z = df1.drop(['year','읍면동명','자치구','선거인수','유년부양비','노년부양비','종사자수','사업체 창업률','기초수급자인원수','보육시설','금융기관','사업체 평균연령','인구','면적'],axis=1)

plt.rc('font', family='Malgun Gothic')

fig = plt.figure(figsize=[20,20])

ax=sns.heatmap(z.corr(),annot=True,square=True)

In [33]:
print(rf1.score(x_train, y_train))

0.8146555349400233


In [34]:
a=['인구밀도','사업체수','장애등급','독거노인수','노령화지수']
for i in range(5):
    final[a[i]]=final[a[i]].fillna(final[a[i]].median())


In [35]:
final_x = final.drop(final.columns[0:2],axis=1)

In [36]:
predict1 = rf1.predict(final_x)

In [38]:
df4 = pd.DataFrame(predict1,columns=['새누리당'])


In [40]:
df5 = final.drop(final.columns[2:],axis=1)

In [41]:
final1 = pd.concat([df5,df4],axis=1)

In [42]:
predicted

array([3043.23118777, 2093.08666559, 4911.10679928, 5673.10445635,
       4888.8618203 , 4424.27157113, 5583.42181463, 3245.06417521,
       3815.41213374, 3434.48806192, 4364.27115386,  996.59310992,
       2834.34594363, 3087.42350511, 5810.71405463, 3841.01970552,
       4156.60909102, 5823.27266562, 4038.22620053, 1726.66641918,
       3071.26514886, 7882.44339477, 3220.82087471, 3497.34076623,
       4186.19042358, 3142.69251472, 3403.46749962, 6605.90262797,
       4686.43901316, 5435.1519135 , 5385.1059696 , 3340.35502177,
       4392.45543145, 3374.31311152, 6814.68198302, 7272.41104554,
       5208.49910667, 3544.43702731, 2639.44040153, 5980.32489631,
       4443.60208778, 3574.79327127, 3431.35641998, 6451.24273013,
       6042.57116807, 1765.41126303, 4486.58882845, 6139.09369028,
       7444.98247615, 3995.77475567, 3709.55700193, 4420.66178774,
       4643.89051182, 4983.26868427, 3507.13973226, 5346.33457858,
       6099.24609926, 2034.85362721, 5970.6017433 , 2192.47284

In [43]:
final1

읍면동명  자치구         새누리당
0        신사동  강남구  1872.491485
1        신사동  관악구  3302.858899
2       논현1동  강남구  2146.306605
3       논현2동  강남구  2146.306605
4       압구정동  강남구  2146.306605
5        청담동  강남구  2146.306605
6       역삼1동  강남구  3087.417318
7       역삼2동  강남구  2825.006397
8       삼성1동  강남구  1428.642455
9       삼성2동  강남구  2039.590286
10      대치1동  강남구  1357.814337
11      대치2동  강남구  3205.476258
12      대치4동  강남구  1765.775167
13      도곡1동  강남구  1879.490306
14      도곡2동  강남구  2153.305426
15      개포1동  강남구  1258.243670
16      개포2동  강남구  1141.284972
17      개포4동  강남구  2153.305426
18      일원본동  강남구  3411.565618
19      일원1동  강남구  4093.443850
20      일원2동  강남구  3992.480215
21       수서동  강남구  3914.983164
22       세곡동  강남구  3959.520450
23       강일동  강동구  4557.206908
24       상일동  강동구  2056.826026
25      명일1동  강동구  2910.028418
26      명일2동  강동구  2075.478487
27      고덕1동  강동구  2804.146120
28      고덕2동  강동구  2124.374572
29      암사1동  강동구  4798.473809
..       ...  ...          ...
394      광희동   중구  1531.608392
395     을지로동   중구  1207.840211
396      신당동   중구  1835.152054
397      다산동   중구  2737.791958
398      약수동   중구  3309.197667
399      청구동   중구  2744.130727
400     신당5동   중구  1738.338385
401      동화동   중구  1783.010907
402      황학동   중구  2153.305426
403      중림동   중구  2056.826026
404    금호1가동   중구  3007.120619
405  금호2.3가동   중구  3007.120619
406    금호4가동   중구  3007.120619
407      옥수동   중구  3007.120619
408     면목본동  중랑구  4871.762384
409     면목2동  중랑구  4536.113916
410   면목3.8동  중랑구  4499.773482
411     면목4동  중랑구  4348.547224
412     면목5동  중랑구  1858.949122
413     면목7동  중랑구  4043.372202
414     상봉2동  중랑구  2854.322325
415     망우3동  중랑구  3692.098008
416     상봉1동  중랑구  4403.472083
417     중화1동  중랑구  3251.910831
418     중화2동  중랑구  4798.473809
419      묵1동  중랑구  4447.395937
420      묵2동  중랑구  3444.010820
421     망우본동  중랑구  4257.209088
422     신내1동  중랑구  4292.422018
423     신내2동  중랑구  4144.861464

[424 rows x 3 columns]

In [44]:
# 더불어 민주당 예측하기!

x2 = df1.drop(['year','읍면동명','자치구','새누리당','더불어민주당','국민의당','선거인수','유년부양비','노년부양비','종사자수','사업체 창업률','기초수급자인원수','보육시설','금융기관','사업체 평균연령','인구','면적'],axis=1)
y2 = df1['더불어민주당']

x2_train, x2_test , y2_train , y2_test = train_test_split(x2,y2,test_size=0.2,random_state=1)

In [45]:
rf2 = RandomForestRegressor()

rf2.fit(x2_train, y2_train)


C:\Users\Hosik\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [46]:
predict2 = rf2.predict(final_x)

In [47]:
predict2

array([1581.3, 1983.8, 1927.7, 1958.1, 1958.1, 1938.5, 1613.2, 2429. ,
       1443.4, 1938.5, 1244.7, 2582.5, 1384.6, 1656.6, 2111.6, 1751. ,
       1558.7, 2111.6, 2254.7, 3920.5, 2622.2, 3377.4, 2538.9, 1967.1,
       2318.8, 1245.7, 2286.3, 2330.3, 2092. , 3685. , 2455.4, 2770.9,
       2851. , 2441.5, 2851. , 2875.2, 2215. , 3896.6, 2423.1,  806.8,
       2874.6, 3044.1, 2101.2, 2310.3, 2989.3, 3067.3, 3030.7, 3377.4,
       1967.1, 3573.1, 3395.4, 3344.3, 2908.3, 2538.9, 2851. , 1582.3,
       1448.5, 2989.3, 3052.1, 2297.7, 3903.1, 1057.6, 2294.4, 2310.3,
       2741. , 3044.1, 2247.5, 2373.5, 1511.2, 1318.3, 3920.5, 2851. ,
       2510.3, 2538.9, 2989.3, 3655.5, 1967.1, 2494.3, 2959.2, 3256.8,
       2685.4, 2286.3, 2183.8, 2441.7, 2092. , 1425.1, 2441.5, 1916. ,
       2254.7, 1301.6, 1797.1, 1667. , 1967.1, 1021.7, 1541.6, 2194.6,
       1166.9, 2575.6, 1384.6, 2965.4, 1166.9, 1245.7, 1521.3, 1511.2,
       2194.6, 3034.7, 1667. , 3002. , 1938.5, 2640.4, 2444.4, 3045.2,
      

In [48]:
#국민의당 예측!

x3 = df1.drop(['year','읍면동명','자치구','새누리당','더불어민주당','국민의당','선거인수','유년부양비','노년부양비','종사자수','사업체 창업률','기초수급자인원수','보육시설','금융기관','사업체 평균연령','인구','면적'],axis=1)
y3 = df1['국민의당']

x3_train, x3_test , y3_train , y3_test = train_test_split(x3,y3,test_size=0.2,random_state=1)

In [49]:
rf3 = RandomForestRegressor()

rf3.fit(x3_train, y3_train)


C:\Users\Hosik\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [50]:
predict3 = rf3.predict(final_x)

In [51]:
predict3

array([4297.2, 4402.2, 4297.2, 4297.2, 4297.2, 4297.2, 4094.1, 4297.2,
       4297.2, 4297.2, 4402.2, 4297.2, 4297.2, 4210.6, 4306.3, 4402.2,
       4402.2, 3782.6, 4402.2, 3782.6, 4402.2, 4879.5, 5034.9, 3909.3,
       4402.2, 4235. , 4402.2, 4402.2, 4235. , 3964.3, 4402.2, 4402.2,
       5029.9, 3742.1, 4524.4, 3813.4, 3737.1, 3737.1, 3891.7, 4402.2,
       4235. , 4210.6, 3909.3, 3909.3, 4402.2, 3891.7, 4402.2, 4462.2,
       3909.3, 4235. , 3244.2, 3244.2, 3909.3, 5034.9, 5029.9, 4402.2,
       4402.2, 4402.2, 3717.7, 3093.3, 3782.6, 3737.1, 4402.2, 3909.3,
       4402.2, 4306.3, 4629.4, 4691.6, 4297.2, 5117. , 3737.1, 4118.9,
       3804.3, 5034.9, 4402.2, 4462.2, 3909.3, 4402.2, 4402.2, 4402.2,
       4306.3, 4402.2, 4402.2, 4402.2, 4235. , 3586.2, 3742.1, 3909.3,
       4402.2, 4402.2, 4402.2, 4402.2, 3909.3, 4235. , 4235. , 4235. ,
       4402.2, 3742.1, 4402.2, 4402.2, 4402.2, 4235. , 4306.3, 3891.7,
       4210.6, 4402.2, 4402.2, 3737.1, 3891.7, 3891.7, 3909.3, 3717.7,
      

In [52]:
#더불어민주당을 새누리당에 추가하기
df7 = pd.DataFrame(predict2,columns=['더불어민주당'])

In [53]:
final2 = pd.concat([final1,df7],axis=1)

In [54]:
final2

읍면동명  자치구         새누리당  더불어민주당
0        신사동  강남구  1872.491485  1581.3
1        신사동  관악구  3302.858899  1983.8
2       논현1동  강남구  2146.306605  1927.7
3       논현2동  강남구  2146.306605  1958.1
4       압구정동  강남구  2146.306605  1958.1
5        청담동  강남구  2146.306605  1938.5
6       역삼1동  강남구  3087.417318  1613.2
7       역삼2동  강남구  2825.006397  2429.0
8       삼성1동  강남구  1428.642455  1443.4
9       삼성2동  강남구  2039.590286  1938.5
10      대치1동  강남구  1357.814337  1244.7
11      대치2동  강남구  3205.476258  2582.5
12      대치4동  강남구  1765.775167  1384.6
13      도곡1동  강남구  1879.490306  1656.6
14      도곡2동  강남구  2153.305426  2111.6
15      개포1동  강남구  1258.243670  1751.0
16      개포2동  강남구  1141.284972  1558.7
17      개포4동  강남구  2153.305426  2111.6
18      일원본동  강남구  3411.565618  2254.7
19      일원1동  강남구  4093.443850  3920.5
20      일원2동  강남구  3992.480215  2622.2
21       수서동  강남구  3914.983164  3377.4
22       세곡동  강남구  3959.520450  2538.9
23       강일동  강동구  4557.206908  1967.1
24       상일동  강동구  2056.826026  2318.8
25      명일1동  강동구  2910.028418  1245.7
26      명일2동  강동구  2075.478487  2286.3
27      고덕1동  강동구  2804.146120  2330.3
28      고덕2동  강동구  2124.374572  2092.0
29      암사1동  강동구  4798.473809  3685.0
..       ...  ...          ...     ...
394      광희동   중구  1531.608392   907.2
395     을지로동   중구  1207.840211   562.1
396      신당동   중구  1835.152054  1360.7
397      다산동   중구  2737.791958  2398.6
398      약수동   중구  3309.197667  2320.4
399      청구동   중구  2744.130727  2660.9
400     신당5동   중구  1738.338385  2217.4
401      동화동   중구  1783.010907  1722.0
402      황학동   중구  2153.305426  2111.6
403      중림동   중구  2056.826026  2318.8
404    금호1가동   중구  3007.120619  1326.4
405  금호2.3가동   중구  3007.120619  1326.4
406    금호4가동   중구  3007.120619  1326.4
407      옥수동   중구  3007.120619  1326.4
408     면목본동  중랑구  4871.762384  2805.4
409     면목2동  중랑구  4536.113916  3529.5
410   면목3.8동  중랑구  4499.773482  4050.5
411     면목4동  중랑구  4348.547224  2622.2
412     면목5동  중랑구  1858.949122  2455.4
413     면목7동  중랑구  4043.372202  3239.4
414     상봉2동  중랑구  2854.322325  1143.7
415     망우3동  중랑구  3692.098008  2826.0
416     상봉1동  중랑구  4403.472083  1967.1
417     중화1동  중랑구  3251.910831  1813.9
418     중화2동  중랑구  4798.473809  3413.5
419      묵1동  중랑구  4447.395937  2441.5
420      묵2동  중랑구  3444.010820  2203.5
421     망우본동  중랑구  4257.209088  2851.0
422     신내1동  중랑구  4292.422018  3830.7
423     신내2동  중랑구  4144.861464  1967.1

[424 rows x 4 columns]

In [1]:
final2.to_csv('final_predict_y.csv',index=False)

NameError: name 'final2' is not defined